version: '3.8'

services:
  play-static:
    image: nginx:alpine
    volumes:
      - ./html:/usr/share/nginx/html:ro
    ports:
      - "${PLAY_PORT:-8080}:80"
    networks:
      - web
    deploy:
      labels:
        - "traefik.enable=true"
        # HTTP router (redirects to HTTPS)
        - "traefik.http.routers.play-http.rule=Host(`${PLAY_DOMAIN:-${DOMAIN}}`)"
        - "traefik.http.routers.play-http.entrypoints=web"
        - "traefik.http.routers.play-http.middlewares=redirect-to-https"
        # HTTPS router
        - "traefik.http.routers.play-https.rule=Host(`${PLAY_DOMAIN:-${DOMAIN}}`)"
        - "traefik.http.routers.play-https.entrypoints=websecure"
        - "traefik.http.routers.play-https.tls=true"
        - "traefik.http.routers.play-https.tls.certresolver=letsencrypt"
        - "traefik.http.services.play.loadbalancer.server.port=80"
        # Middleware for HTTP to HTTPS redirect
        - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
        - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  web:
    external: true