version: '3.8'

services:
  odoo-postgres:
    image: postgres:16
    environment:
      - POSTGRES_DB=${ODOO_DB_NAME}
      - POSTGRES_USER=${ODOO_DB_USER}
      - POSTGRES_PASSWORD=${ODOO_DB_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./postgres/data:/var/lib/postgresql/data/pgdata
    networks:
      - odoo-internal
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager

  odoo:
    image: odoo:19
    environment:
      - HOST=odoo-postgres
      - USER=${ODOO_DB_USER}
      - PASSWORD=${ODOO_DB_PASSWORD}
    volumes:
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
      - odoo_web_data:/var/lib/odoo
    networks:
      - web
      - odoo-internal
    depends_on:
      - odoo-postgres
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.odoo.rule=Host(`${ODOO_DOMAIN}`)"
        - "traefik.http.routers.odoo.entrypoints=websecure"
        - "traefik.http.routers.odoo.tls.certresolver=letsencrypt"
        - "traefik.http.services.odoo.loadbalancer.server.port=8069"
        - "traefik.docker.network=web"
        - "traefik.http.routers.odoo-longpolling.rule=Host(`${ODOO_DOMAIN}`) && PathPrefix(`/longpolling`)"
        - "traefik.http.routers.odoo-longpolling.entrypoints=websecure"
        - "traefik.http.routers.odoo-longpolling.tls.certresolver=letsencrypt"
        - "traefik.http.services.odoo-longpolling.loadbalancer.server.port=8072"
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager

networks:
  web:
    external: true
  odoo-internal:
    driver: overlay

volumes:
  odoo_web_data:
  odoo_db_data:
  odoo_addons:

