version: '3.8'

services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    environment:
      - AUDIOBOOKSHELF_UID=${AUDIOBOOKSHELF_UID}
      - AUDIOBOOKSHELF_GID=${AUDIOBOOKSHELF_GID}
    volumes:
      - ./audiobooks:/audiobooks
      - ./config:/config
      - ./metadata:/metadata
    ports:
      - "${AUDIOBOOKSHELF_PORT}:80"
    networks:
      - web
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.audiobookshelf-http.rule=Host(`${AUDIOBOOKSHELF_DOMAIN}`)"
        - "traefik.http.routers.audiobookshelf-http.entrypoints=web"
        - "traefik.http.routers.audiobookshelf-http.middlewares=redirect-to-https"
        - "traefik.http.routers.audiobookshelf-https.rule=Host(`${AUDIOBOOKSHELF_DOMAIN}`)"
        - "traefik.http.routers.audiobookshelf-https.entrypoints=websecure"
        - "traefik.http.routers.audiobookshelf-https.tls=true"
        - "traefik.http.routers.audiobookshelf-https.tls.certresolver=letsencrypt"
        - "traefik.http.services.audiobookshelf.loadbalancer.server.port=80"
        - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
        - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager

networks:
  web:
    external: true

